from tkinter import*
from tkinter import messagebox
import mysql.connector
conn=mysql.connector.connect(host="localhost",user="root",password="Gayathri###333",database="python_db")
cursor=conn.cursor()
cursor.execute()
print("connection established")
m=Tk()
m.geometry("800x800")
m.config(background='#ff99bb')
def hello():
    messagebox.showinfo("MEDICAL FORM","SUCCESFULLY REGISTERED")

a=Label(m,text="CHILD MEDICAL AUTHORIZATION FORM",fg="white",bg="brown",font=("goudy stout",15)).place(x=300,y=20)
Label(m,text="LEGAL GUARDIAN NAME:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=100)
Entry(m).place(x=200,y=130)
Label(m,text="CHILD NAME:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=160)
Entry(m).place(x=200,y=190)
Label(m,text="BIRTH DATE:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=230)
Entry(m).place(x=200,y=260)
Label(m,text="CARE GIVER NAME:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=290)
Entry(m).place(x=200,y=320)
Label(m,text="AUTHORIZATION APPLY TO:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=350)
Label(m,text="Surgery",fg="white",bg="black",font=("cambria",12)).place(x=200,y=380)
Checkbutton().place(x=400,y=380)
Label(m,text="Hospitalization",fg="white",bg="black",font=("cambria",12)).place(x=200,y=410)
Checkbutton().place(x=400,y=410)
Label(m,text="Dental care & treatment",fg="white",bg="black",font=("cambria",12)).place(x=200,y=440)
Checkbutton().place(x=400,y=440)
Label(m,text="Blood transfusion",fg="white",bg="black",font=("cambria",12)).place(x=200,y=470)
Checkbutton().place(x=400,y=470)
Label(m,text="Routine medical treatment",fg="white",bg="black",font=("cambria",12)).place(x=200,y=500)
Checkbutton().place(x=400,y=500)
Label(m,text="START DATE:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=540)
Entry(m).place(x=200,y=580)
Label(m,text="TERMINATION DATE:",fg="orange",bg="black",font=("cambria",12)).place(x=200,y=610)
Entry(m).place(x=200,y=640)
Label(m,text="AGE:",fg="orange",bg="black",font=("cambria",12)).place(x=600,y=100)
Spinbox(m,from_=0,to=80).place(x=650,y=100)
Label(m,text="GENDER:",fg="orange",bg="black",font=("cambria",12)).place(x=600,y=150)
var=IntVar()
Radiobutton(m,text="Male",value=1,variable=var).place(x=600,y=180)
var1=IntVar()
Radiobutton(m,text="Female",value=1,variable=var1).place(x=600,y=220)
Label(m,text="SIGNATURE:",fg="orange",bg="black",font=("cambria",12)).place(x=600,y=260)
Entry(m).place(x=710,y=260)
Button(m,text="SUBMIT",command=hello,fg="white",bg="black",font=("cambria",12)).place(x=600,y=360)
m.mainloop()
